ruby-version/customer-service/config/routes.rb
Rails.application.routes.draw do
  resources :customers
  get '/api/v1/customers', to: 'customers#get_customers'
end

ruby-version/customer-service/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby-version/customer-service/app/models/customer.rb
class Customer < ApplicationRecord
end

ruby-version/customer-service/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby-version/customer-service/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if Customer.find_by_name(params[:name])
      raise 'error'
    end

    if @customer.save
      redirect_to @customer
    else
      render 'new'
    end
  end

  def show
    @customer = Customer.find(params[:id])

    redirect_to customers_path
  end

  def index

    @customers = Customer.all
  end

  def destroy
    @article = Customer.find(params[:id])
    @article.destroy

    redirect_to customers_path
  end

  def get_customers
    response.headers['Content-Type'] = 'application/json'
    render  json: Customer.all
  end

  private
    def customer_params
      params.require(:customer).permit(:name, :email)
    end
end

ruby-version/customer-service/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby-version/customer-service/app/helpers/customers_helper.rb
module CustomersHelper
end

ruby-version/customer-service/app/views/customers/_form.html.erb
<%= form_with model: @customer, local: true do |form| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@customer.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_area :email %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

ruby-version/customer-service/app/views/customers/index.html.erb
<h1>Listing Customers</h1>

<%= link_to 'Create Customer', new_customer_path%>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th colspan="2"></th>
  </tr>

  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.name %></td>
      <td><%= customer.email %></td>
      <td><%= link_to 'Destroy', customer_path(customer),
                      method: :delete,
                      data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

ruby-version/customer-service/app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

ruby-version/customer-service/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomerService</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>